version: '3.1'
services:
  proxy:
    image: 'nginx:1.19.2-alpine'
    restart: always
    volumes:
      - './.config/nginx.docker.conf:/etc/nginx/conf.d/default.conf'
    depends_on: [ auth, task ]
    ports:
      - '80:80'

  auth:
    build:
      context: src/auth
      dockerfile: Dockerfile
    depends_on:
      - postgre

  task:
    build:
      context: src/tasks
      dockerfile: Dockerfile
    depends_on:
      - postgre

  postgre:
      image: postgres
      environment:
        POSTGRES_PASSWORD: password

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
      image: confluentinc/cp-kafka:7.0.1
      restart: always
      ports:
        - "9093:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

