version: '3.1'
services:
  proxy:
    image: 'nginx:1.19.2-alpine'
    restart: always
    volumes:
      - './.config/nginx.docker.conf:/etc/nginx/conf.d/default.conf'
    depends_on: [ auth, task ]
    ports:
      - '80:80'


  auth:
    build:
      context: src/auth
      dockerfile: Dockerfile
    depends_on:
      - postgre

  task:
    build:
      context: src/tasks
      dockerfile: Dockerfile
    depends_on:
      - postgre

  postgre:
      image: postgres
      environment:
        POSTGRES_PASSWORD: password

