// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateTaskRes interface {
	createTaskRes()
}

type DeleteTaskRes interface {
	deleteTaskRes()
}

type ListTaskRes interface {
	listTaskRes()
}

type ListUserTasksRes interface {
	listUserTasksRes()
}

type ReadTaskAssignedRes interface {
	readTaskAssignedRes()
}

type ReadTaskRes interface {
	readTaskRes()
}

type UpdateTaskRes interface {
	updateTaskRes()
}
