// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"math"
	"math/big"
	"math/bits"
	"net"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

// No-op definition for keeping imports.
var (
	_ = context.Background()
	_ = fmt.Stringer(nil)
	_ = strings.Builder{}
	_ = errors.Is
	_ = sort.Ints
	_ = http.MethodGet
	_ = io.Copy
	_ = json.Marshal
	_ = bytes.NewReader
	_ = strconv.ParseInt
	_ = time.Time{}
	_ = conv.ToInt32
	_ = uuid.UUID{}
	_ = uri.PathEncoder{}
	_ = url.URL{}
	_ = math.Mod
	_ = bits.LeadingZeros64
	_ = big.Rat{}
	_ = validate.Int{}
	_ = ht.NewRequest
	_ = net.IP{}
	_ = otelogen.Version
	_ = attribute.KeyValue{}
	_ = trace.TraceIDFromHex
	_ = otel.GetTracerProvider
	_ = metric.NewNoopMeterProvider
	_ = regexp.MustCompile
	_ = jx.Null
	_ = sync.Pool{}
	_ = codes.Unset
)

type CreateTaskReq struct {
	Title       string    "json:\"title\""
	Description string    "json:\"description\""
	Assigned    OptString "json:\"assigned\""
}

// DeleteTaskNoContent is response for DeleteTask operation.
type DeleteTaskNoContent struct{}

func (*DeleteTaskNoContent) deleteTaskRes() {}

type ListTaskOKApplicationJSON []TaskList

func (ListTaskOKApplicationJSON) listTaskRes() {}

type ListUserTasksOKApplicationJSON []UserTasksList

func (ListUserTasksOKApplicationJSON) listUserTasksRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type R400 struct {
	Code   int    "json:\"code\""
	Status string "json:\"status\""
	Errors jx.Raw "json:\"errors\""
}

func (*R400) createTaskRes()       {}
func (*R400) deleteTaskRes()       {}
func (*R400) listTaskRes()         {}
func (*R400) listUserTasksRes()    {}
func (*R400) readTaskAssignedRes() {}
func (*R400) readTaskRes()         {}
func (*R400) updateTaskRes()       {}

type R404 struct {
	Code   int    "json:\"code\""
	Status string "json:\"status\""
	Errors jx.Raw "json:\"errors\""
}

func (*R404) deleteTaskRes()       {}
func (*R404) listTaskRes()         {}
func (*R404) listUserTasksRes()    {}
func (*R404) readTaskAssignedRes() {}
func (*R404) readTaskRes()         {}
func (*R404) updateTaskRes()       {}

type R409 struct {
	Code   int    "json:\"code\""
	Status string "json:\"status\""
	Errors jx.Raw "json:\"errors\""
}

func (*R409) createTaskRes()       {}
func (*R409) deleteTaskRes()       {}
func (*R409) listTaskRes()         {}
func (*R409) listUserTasksRes()    {}
func (*R409) readTaskAssignedRes() {}
func (*R409) readTaskRes()         {}
func (*R409) updateTaskRes()       {}

type R500 struct {
	Code   int    "json:\"code\""
	Status string "json:\"status\""
	Errors jx.Raw "json:\"errors\""
}

func (*R500) createTaskRes()       {}
func (*R500) deleteTaskRes()       {}
func (*R500) listTaskRes()         {}
func (*R500) listUserTasksRes()    {}
func (*R500) readTaskAssignedRes() {}
func (*R500) readTaskRes()         {}
func (*R500) updateTaskRes()       {}

// Ref: #/components/schemas/Task_AssignedRead
type TaskAssignedRead struct {
	ID    string "json:\"id\""
	Login string "json:\"login\""
}

func (*TaskAssignedRead) readTaskAssignedRes() {}

// Ref: #/components/schemas/TaskCreate
type TaskCreate struct {
	ID          int       "json:\"id\""
	Title       string    "json:\"title\""
	Description string    "json:\"description\""
	IsDone      OptBool   "json:\"is_done\""
	CreatedAt   time.Time "json:\"created_at\""
	UpdatedAt   time.Time "json:\"updated_at\""
	AssignedID  OptString "json:\"assigned_id\""
}

func (*TaskCreate) createTaskRes() {}

// Ref: #/components/schemas/TaskList
type TaskList struct {
	ID          int       "json:\"id\""
	Title       string    "json:\"title\""
	Description string    "json:\"description\""
	IsDone      OptBool   "json:\"is_done\""
	CreatedAt   time.Time "json:\"created_at\""
	UpdatedAt   time.Time "json:\"updated_at\""
	AssignedID  OptString "json:\"assigned_id\""
}

// Ref: #/components/schemas/TaskRead
type TaskRead struct {
	ID          int       "json:\"id\""
	Title       string    "json:\"title\""
	Description string    "json:\"description\""
	IsDone      OptBool   "json:\"is_done\""
	CreatedAt   time.Time "json:\"created_at\""
	UpdatedAt   time.Time "json:\"updated_at\""
	AssignedID  OptString "json:\"assigned_id\""
}

func (*TaskRead) readTaskRes() {}

// Ref: #/components/schemas/TaskUpdate
type TaskUpdate struct {
	ID          int       "json:\"id\""
	Title       string    "json:\"title\""
	Description string    "json:\"description\""
	IsDone      OptBool   "json:\"is_done\""
	CreatedAt   time.Time "json:\"created_at\""
	UpdatedAt   time.Time "json:\"updated_at\""
	AssignedID  OptString "json:\"assigned_id\""
}

func (*TaskUpdate) updateTaskRes() {}

type UpdateTaskReq struct {
	Title       OptString "json:\"title\""
	Description OptString "json:\"description\""
	Assigned    OptString "json:\"assigned\""
}

// Ref: #/components/schemas/User_TasksList
type UserTasksList struct {
	ID          int       "json:\"id\""
	Title       string    "json:\"title\""
	Description string    "json:\"description\""
	IsDone      OptBool   "json:\"is_done\""
	CreatedAt   time.Time "json:\"created_at\""
	UpdatedAt   time.Time "json:\"updated_at\""
	AssignedID  OptString "json:\"assigned_id\""
}
